// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @notice The Poseidon(2) hasher. Deployed from circomlib-generated bytecode so it
///         matches the Poseidon used inside the withdraw circuit bit-for-bit.
interface IHasher {
    function poseidon(uint256[2] calldata input) external pure returns (uint256);
}

/**
 * @title MerkleTreeWithHistory
 * @notice Append-only, fixed-depth incremental Merkle tree using Poseidon, with a
 *         rolling history of recent roots.
 *
 * Every deposit's commitment is inserted as the next leaf. Withdrawals prove
 * Merkle inclusion against any of the last `ROOT_HISTORY_SIZE` roots, so honest
 * withdrawals don't fail when other deposits land between proving and submitting.
 *
 * Adapted from Tornado Cash's MerkleTreeWithHistory, using Poseidon instead of MiMC
 * and computing the zero-subtree values in the constructor.
 */
contract MerkleTreeWithHistory {
    error LevelsOutOfRange(uint32 levels);
    error LeftOutOfField(uint256 value);
    error RightOutOfField(uint256 value);
    error TreeFull();

    // BN254 scalar field — every node value must be a valid field element.
    uint256 public constant FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    uint32 public constant ROOT_HISTORY_SIZE = 30;

    IHasher public immutable hasher;
    uint32 public immutable levels;
    uint256 public immutable ZERO_VALUE;

    // zeros[i] = root of an all-empty subtree of height i
    mapping(uint256 => uint256) public zeros;
    // filledSubtrees[i] = last-known left-sibling at level i, used during insertion
    mapping(uint256 => uint256) public filledSubtrees;
    // ring buffer of recent roots
    mapping(uint256 => uint256) public roots;

    uint32 public currentRootIndex;
    uint32 public nextIndex;

    constructor(uint32 _levels, IHasher _hasher) {
        if (_levels == 0 || _levels >= 32) revert LevelsOutOfRange(_levels);
        levels = _levels;
        hasher = _hasher;

        // A fixed, domain-separated empty-leaf value that cannot collide with a real
        // commitment = Poseidon(nullifier, secret) except with negligible probability.
        uint256 zero = uint256(keccak256(abi.encodePacked("obsidian"))) % FIELD_SIZE;
        ZERO_VALUE = zero;

        uint256 currentZero = zero;
        for (uint32 i = 0; i < _levels; i++) {
            zeros[i] = currentZero;
            filledSubtrees[i] = currentZero;
            currentZero = hashLeftRight(currentZero, currentZero);
        }

        // root of the empty tree
        roots[0] = currentZero;
    }

    /// @notice Poseidon hash of an ordered pair, via the on-chain hasher.
    function hashLeftRight(uint256 _left, uint256 _right) public view returns (uint256) {
        if (_left >= FIELD_SIZE) revert LeftOutOfField(_left);
        if (_right >= FIELD_SIZE) revert RightOutOfField(_right);
        return hasher.poseidon([_left, _right]);
    }

    /// @notice Insert a leaf and advance the tree. Returns the leaf's index.
    function _insert(uint256 _leaf) internal returns (uint32 index) {
        uint32 _nextIndex = nextIndex;
        if (_nextIndex == uint32(2) ** levels) revert TreeFull();

        uint32 currentIndex = _nextIndex;
        uint256 currentLevelHash = _leaf;
        uint256 left;
        uint256 right;

        for (uint32 i = 0; i < levels; i++) {
            if (currentIndex % 2 == 0) {
                // current node is a left child; its right sibling is still empty
                left = currentLevelHash;
                right = zeros[i];
                filledSubtrees[i] = currentLevelHash;
            } else {
                // current node is a right child; its left sibling is the last filled one
                left = filledSubtrees[i];
                right = currentLevelHash;
            }
            currentLevelHash = hashLeftRight(left, right);
            currentIndex /= 2;
        }

        uint32 newRootIndex = (currentRootIndex + 1) % ROOT_HISTORY_SIZE;
        currentRootIndex = newRootIndex;
        roots[newRootIndex] = currentLevelHash;
        nextIndex = _nextIndex + 1;
        return _nextIndex;
    }

    /// @notice True if `_root` is among the last ROOT_HISTORY_SIZE roots.
    function isKnownRoot(uint256 _root) public view returns (bool) {
        if (_root == 0) {
            return false;
        }
        uint32 _currentRootIndex = currentRootIndex;
        uint32 i = _currentRootIndex;
        do {
            if (_root == roots[i]) {
                return true;
            }
            if (i == 0) {
                i = ROOT_HISTORY_SIZE;
            }
            i--;
        } while (i != _currentRootIndex);
        return false;
    }

    /// @notice The most recent root.
    function getLastRoot() public view returns (uint256) {
        return roots[currentRootIndex];
    }
}
