import { HardhatRuntimeEnvironment } from 'hardhat/types';
import { DeployFunction } from 'hardhat-deploy/types';
import { ethers } from 'hardhat';
import 'hardhat-deploy';
// circomlibjs ships no type declarations
// @ts-ignore
import { poseidonContract } from 'circomlibjs';

/**
 * @title Deploy the Poseidon(2) hasher
 * @dev Deployed from circomlib-generated bytecode so the on-chain hash matches the
 *      Poseidon used inside the withdraw circuit bit-for-bit. There is no .sol source,
 *      so we deploy the bytecode directly and record it via deployments.save().
 */
const deployPoseidon: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
    const { deployments, getNamedAccounts } = hre;
    const { log, save, getOrNull } = deployments;
    const { deployer } = await getNamedAccounts();

    const existing = await getOrNull('Poseidon');
    if (existing) {
        log(`Poseidon already deployed at ${existing.address}`);
        return;
    }

    const abi = poseidonContract.generateABI(2);
    const bytecode = poseidonContract.createCode(2);

    const signer = await ethers.getSigner(deployer);
    const factory = new ethers.ContractFactory(abi, bytecode, signer);
    const poseidon = await factory.deploy();
    await poseidon.waitForDeployment();
    const address = await poseidon.getAddress();

    await save('Poseidon', { address, abi });
    log(`Poseidon(2) hasher deployed at ${address}`);
};

export default deployPoseidon;
deployPoseidon.tags = ['poseidon', 'main', 'core'];
